version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    restart: always